[package]
name = "bno08x"
description = "BNO08x IMU Driver for ADIS"
repository = "https://bitbucket.org/au-zone/bno08x-rs/src/master/"
version = "0.0.1"
edition = "2021"
readme = "README.md"

[[bin]]
name = "bno08x"
path = "src/main.rs"

[[bin]]
name = "bno08x-frs"
path = "src/frs.rs"

[lib]
name = "bno08x"
path = "src/lib.rs"

[dependencies]
spidev = "0.5.1"
gpiod = "0.2.3"

[features]
default = []
