[package]
name = "bno080"
description = "ADIS Logging Service"
repository = "https://bitbucket.org/au-zone/adis-logger"
version = "0.2.3"
edition = "2021"
readme = "README.md"

[[bin]]
name = "bno080"
path = "src/main.rs"

[lib]
name = "bno080"
path = "src/lib.rs"

[dependencies]
spidev = "0.5.1"
gpiod = "0.2.3"

[features]
default = []
